# Overrides for local development
version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000" # Expose port 8000 to the host
    env_file:
      - ./backend/.env # Use local development environment variables
    volumes:
      - ./backend:/app # Mount local code for hot-reloading
    command: python manage.py runserver 0.0.0.0:8000 # Use the development server

  frontend:
    build:
      context: ./frontend/web_app
      target: build # Use the 'build' stage with Node.js for development
    ports:
      - "5173:5173" # Expose the Vite dev server port
    env_file:
      - ./frontend/web_app/.env # Use local development environment variables
    volumes:
      - ./frontend/web_app:/app # Mount local code for hot-reloading
      - node_modules:/app/node_modules # Persist node_modules
    command: npm run dev # Start the Vite dev server
